on: push
jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@master
        with:
          path: ~\AppData\Local\vcpkg
          key: vcpkg-cache
      - env:
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
        run: |
          $ErrorActionPreference = "Continue"
          pushd $Env:VCPKG_INSTALLATION_ROOT
          git pull
          git apply "$Env:GITHUB_WORKSPACE\misc\vcpkg-libarchive-slash.patch"
          .\bootstrap-vcpkg.bat
          popd
          vcpkg integrate install
          vcpkg install libarchive boost-program-options boost-format boost-algorithm boost-test tinyxml2
          git fetch --unshallow --tags
          cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" & set' |
            foreach { if ($_ -match "=") { $v = $_.split("="); Set-Item -Force -Path "Env:\$($v[0])" -Value "$($v[1])" } }
          cmake . `
            -G "NMake Makefiles" `
            -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="$Env:VCPKG_DEFAULT_TRIPLET" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_CHOCO_PKG=ON
          nmake
          nmake test
          nmake package
          if ($LASTEXITCODE -ne 0) { Exit 1 }
          $version = git describe --tags
          cmd /c "rename LxRunOffline-$version-msvc.zip LxRunOffline-msvc.zip"
      - uses: actions/upload-artifact@v3
        with:
          name: LxRunOffline-msvc.zip
          path: LxRunOffline-msvc.zip
